# local configuration
server:
  port: 8082
grpc:
  server:
    port: 9091
  client:
    order-service:
      address: static://localhost:9090
      negotiationType: plaintext



# remote server configuration
remote:
  server:
    grpc:
      host: localhost
      port: 9090
    restapi:
      url: http://localhost:8083/product

adapter:
  elapsedTimes:
    file: elapsed-times.csv